version: '3.3'
services:
  app:
    build: ./app
    command: bash -c
      "sleep 3
        && python ./manage.py makemigrations
        && python ./manage.py migrate
        && python ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.7-management

  worker:
    build: ./app
    command: celery -A project worker --loglevel info --concurrency=1 -B
    depends_on:
      - db
      - rabbitmq
    restart: always

volumes:
     pgdata:
